library(dplyr)
library(tidyverse)
library(rlist)
library(RSocrata)
library(rgdal)
library(leaflet)
library(plyr)
library(shiny)
library(shinyWidgets)
library(maps)
library(RColorBrewer)
library(DT)
library(plotly)
library(lattice)
library(shinycssloaders)

districts <- readOGR("~/R/Project 15/Datasets/ShapeFile/CnclDist_July2012.shp")
districts <-spTransform(districts, CRS("+proj=longlat +datum=WGS84 +no_defs"))
bounds<-bbox(districts)

immigrant_data<-readRDS("~/R/Project 15/Data/Data_for_map.rds")

crime2010<-readRDS("~/R/Project 15/Data/crime2010.rds")%>% select("lng"="Xcoord","lat"="Ycoord","DISTRICT"="district")
crime2011<-readRDS("~/R/Project 15/Data/crime2011.rds")%>% select("lng"="Xcoord","lat"="Ycoord","DISTRICT"="district")
crime2012<-readRDS("~/R/Project 15/Data/crime2012.rds")%>% select("lng"="Xcoord","lat"="Ycoord","DISTRICT"="district")
crime2013<-readRDS("~/R/Project 15/Data/crime2013.rds")%>% select("lng"="Xcoord","lat"="Ycoord","DISTRICT"="district")
crime2014<-readRDS("~/R/Project 15/Data/crime2014.rds")%>% select("lng"="Xcoord","lat"="Ycoord","DISTRICT"="district")
crime2015<-readRDS("~/R/Project 15/Data/crime2015.rds")%>% select("lng"="Xcoord","lat"="Ycoord","DISTRICT"="district")
crime2016<-readRDS("~/R/Project 15/Data/crime2016.rds")%>% select("lng"="Xcoord","lat"="Ycoord","DISTRICT"="district")
